version: 0.2

env:
  secrets-manager:
    TOKEN: "firstSecret:tokenForSonar"   # secret-name : json-key

phases:
  install:
    runtime-versions:
      # If your image supports runtime selection, this works:
      java: corretto17
      # or: java: latest
  build:
    commands:
      - mvn -v
      - mvn verify sonar:sonar \
          -Dsonar.projectKey=javaprojectawssagi \
          -Dsonar.organization=javaprojectawssagi \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.token="$TOKEN"
