version: 0.2
env:
  secrets-manager:
    TOKEN: "firstSecret:tokenForSonar"
phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - export SONAR_TOKEN="$TOKEN"
  build:
    commands:
      - mvn verify sonar:sonar \
          -Dsonar.projectKey=javaprojectawssagi \
          -Dsonar.organization=javaprojectawssagi \
          -Dsonar.host.url=https://sonarcloud.io
