version: 0.2

env:
  secrets-manager:
    TOKEN: firstSecret:tokenForSonar               
    SNYK_TOKEN: synkAPIKey                         
                     

phases:
  install:
    runtime-versions:
      java: latest
      nodejs: 18
    commands:
      - npm install -g snyk@latest snyk-to-html@latest
      - snyk auth "$SNYK_TOKEN" || true

  build:
    commands:
      # --- SonarCloud  ---
      - mvn -B verify sonar:sonar -Dsonar.projectKey=javaprojectawssagi -Dsonar.organization=javaprojectawssagi -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=$TOKEN
      - sleep 5
      - |
        quality_status=$(curl -s -u $TOKEN: "https://sonarcloud.io/api/qualitygates/project_status?projectKey=javaprojectawssagi" | jq -r '.projectStatus.status')
        echo "SonarCloud analysis status is $quality_status"
        if [ "$quality_status" = "ERROR" ]; then echo "Failing due to Sonar quality gate"; exit 1; fi

      # --- Snyk SCA scan (soft gate) ---
      - echo "Running Snyk SCA..."
      - snyk test --severity-threshold=high --fail-on=all --json > snyk.json || true
      - npx snyk-to-html -i snyk.json -o snyk.html || true
      - echo "Snyk scan completed — report saved as snyk.html"

      # --- OWASPT ZAP DAST integration ---
      - apt-get update
      - apt-get -y install wget
      - apt-get -y install default-jdk
      - wget https://github.com/zaproxy/zaproxy/releases/download/v2.16.0/ZAP_2.16.0_Linux.tar.gz
      - tar -xvf ZAP_2.16.0_Linux.tar.gz
      - cd ZAP_2.16.0
      - ./zap.sh -cmd -quickurl https://www.example.com -quickprogress -quickout ../zap_report.html

artifacts:
  files:
    - snyk.json
    - snyk.html
    - zap_report.html
    - target/**/*
  discard-paths: yes
